services:
  directus:
    image: directus/directus:11.0.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "replace-with-secure-random-value"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "1234"
      DB_CLIENT: "pg"
      DB_HOST: "${POSTGRES_SERVER}"
      DB_PORT: 5432
      DB_DATABASE: "${POSTGRES_DB}"
      DB_USER: "${POSTGRES_USER}"
      DB_PASSWORD: "${POSTGRES_PASSWORD}"
      WEBSOCKETS_ENABLED: "true"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env

  postgres:
    image: postgis/postgis:14-3.3
    healthcheck:
      test: /usr/bin/pg_isready -U postgres
      interval: 5s
      timeout: 10s
      retries: 120
    expose:
      - '5432'
    env_file:
      - .env
    volumes:
      - ./postgres/01-init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh
      - ./postgres/data:/var/lib/postgresql/data
